/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gymmanagementsystem;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.time.LocalDate;
/**
 *
 * @author admin
 */
public class AddMemberConfirmation extends javax.swing.JFrame {
    private Dashboard dashboard;
    private PreparedStatement ps;
    private ResultSet rs;
    /**
     * Creates new form AddMemberConfirmation
     */
    
    public AddMemberConfirmation(String lname, String fname, String subscription, Dashboard dashboard) {
        initComponents();
        this.lnameLabel.setText(lname);
        this.fnameLabel.setText(fname);
        this.subscriptionLabel.setText(subscription);
        this.dashboard  = dashboard;
        
        //Get Duration and Amount
        String getPriceFromSub = "Select duration, price from tbl_subscription where sub_name=?";
        try {
            ps = MyConnection.getConnection().prepareStatement(getPriceFromSub);
            ps.setString(1,subscription);
            rs = ps.executeQuery();
            if (rs.next()){
            String duration = String.valueOf(rs.getInt("duration"));
            String amount = String.valueOf(rs.getInt("price"));
            
            durationLabel.setText(duration);
            amountLabel.setText(amount);
            
            }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lnameLabel = new javax.swing.JLabel();
        fnameLabel = new javax.swing.JLabel();
        subscriptionLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("ADD NEW MEMBER");

        jLabel1.setText("Last Name:");

        jLabel2.setText("First Name:");

        jLabel3.setText("Subsciption Type:");

        jLabel4.setText("Duration:");

        jLabel7.setText("Amount:");

        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lnameLabel.setText("jLabel6");

        fnameLabel.setText("jLabel6");

        subscriptionLabel.setText("jLabel6");

        durationLabel.setText("jLabel6");

        amountLabel.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lnameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fnameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subscriptionLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(durationLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(amountLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(195, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton2)
                        .addContainerGap(136, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameLabel))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subscriptionLabel))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String lname = lnameLabel.getText();
String fname = fnameLabel.getText();
String duration = durationLabel.getText();
String amount = amountLabel.getText();
long days = Long.parseLong(duration);
LocalDate expirationDate = LocalDate.now().plusDays(days);
String mem_id = null;
String sub_id = null;
try {
    // 1. Check for duplicate
    String checkQuery = "SELECT * FROM tbl_member WHERE mem_fname = ? AND mem_lname = ?";
    PreparedStatement ps = MyConnection.getConnection().prepareStatement(checkQuery);
    ps.setString(1, fname);
    ps.setString(2, lname);
    ResultSet rs = ps.executeQuery();

    if(rs.next()) {
        String updateMemberQuery ="UPDATE tbl_member SET expiration_date = ? WHERE mem_lname = ?";
        ps = MyConnection.getConnection().prepareStatement(updateMemberQuery);
        ps.setString(1, expirationDate.toString());
        ps.setString(2, lname);
        ps.executeUpdate();
        
        
        rs.close();
        ps.close();
        //Post Transaction query
        String getMem_idQuery ="SELECT mem_id FROM tbl_member where mem_lname=? AND mem_fname=?";
        ps = MyConnection.getConnection().prepareStatement(getMem_idQuery);
        ps.setString(1, lname);
        ps.setString(2, fname);
        rs = ps.executeQuery();
        if (rs.next()){
        mem_id = String.valueOf(rs.getString("mem_id"));
        }
        rs.close();
        ps.close();
    
        
        
    String getSub_idQuery =" Select sub_id FROM tbl_subscription where duration=?";
    ps = MyConnection.getConnection().prepareStatement(getSub_idQuery);
    ps.setString(1, duration);
    rs = ps.executeQuery();
    if (rs.next()){
    sub_id = String.valueOf(rs.getString("sub_id"));
    }
    rs.close();
    ps.close();
    
    String postTransactionQuery ="INSERT INTO tbl_transaction (mem_id, sub_id, amount) VALUES(?,?,?)";
                
                //Add Log to Database
                ps = MyConnection.getConnection().prepareStatement(postTransactionQuery);
                ps.setString(1, mem_id);
                ps.setString(2, sub_id);
                ps.setString(3, amount);
                ps.executeUpdate();
                
                //Go back to dashboard
                dashboard.populateMemberAndTransactionTable();
                this.dispose();
                
                 JOptionPane.showMessageDialog(null, "Member renewed successfully!");
        return; // stop execution
    }

    rs.close();
    ps.close();

    //Post Member query
    String postMemberQuery = "INSERT INTO tbl_member (mem_lname, mem_fname, expiration_date) VALUES (?, ?, ?)";
    ps = MyConnection.getConnection().prepareStatement(postMemberQuery);
    ps.setString(1, lname);
    ps.setString(2, fname);
    ps.setString(3, expirationDate.toString());
    ps.executeUpdate();
    ps.close();
    
    //Post Transaction query
    String getMem_idQuery ="SELECT mem_id FROM tbl_member where mem_lname=? AND mem_fname=?";
    ps = MyConnection.getConnection().prepareStatement(getMem_idQuery);
    ps.setString(1, lname);
    ps.setString(2, fname);
    rs = ps.executeQuery();
    if (rs.next()){
    mem_id = String.valueOf(rs.getString("mem_id"));
    }
    rs.close();
    ps.close();
    
        
        
    String getSub_idQuery =" Select sub_id FROM tbl_subscription where duration=?";
    ps = MyConnection.getConnection().prepareStatement(getSub_idQuery);
    ps.setString(1, duration);
    rs = ps.executeQuery();
    if (rs.next()){
    sub_id = String.valueOf(rs.getString("sub_id"));
    }
    rs.close();
    ps.close();
    
    String postTransactionQuery ="INSERT INTO tbl_transaction (mem_id, sub_id, amount) VALUES(?,?,?)";
                
                //Add Log to Database
                ps = MyConnection.getConnection().prepareStatement(postTransactionQuery);
                ps.setString(1, mem_id);
                ps.setString(2, sub_id);
                ps.setString(3, amount);
                ps.executeUpdate();
                
                //Go back to dashboard
                dashboard.populateMemberAndTransactionTable();
                this.dispose();
                
    JOptionPane.showMessageDialog(null, "Member added successfully!");

} catch(Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
}

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JLabel subscriptionLabel;
    // End of variables declaration//GEN-END:variables
}
